spring:
  application:
    name: whereabouts

jackson:
  serialization:
    write_dates_as_timestamps: false
    indent_output: true

server:
  port : 8086

---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.use_minimal_puts: true
      hibernate.jdbc.batch_size: 500
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  liquibase:
    enabled: true

keycloak:
  bearer-only: true
  use-resource-role-mappings: true
