spring:
    profiles:
        active: dev
    datasource:
        platform: mysql
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${db_host:localhost}:${db_port:5432}/${db_name:whereabouts}?currentSchema=public
        username: ${db_username:wa}
        password: ${db_password:wa}
        hikari:
            jdbc-url: jdbc:postgresql://${db_host:localhost}:${db_port:5432}/${db_name:whereabouts}
