spring:
    profiles:
        active: dev
    datasource:
        platform: postgres
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${db_host:localhost}:${db_port:5432}/${db_name:whereabouts}?currentSchema=public
        username: ${db_username:wa}
        password: ${db_password:wa}
        hikari:
            jdbc-url: jdbc:postgresql://${db_host:localhost}:${db_port:5432}/${db_name:whereabouts}
---
keycloak:
    bearer-only: true
    use-resource-role-mappings: true
    auth-server-url: http://localhost:8081/auth
    realm: dev
    resource: whereabouts