version: '3'
services:
  whereabouts-database:
    container_name: whereabouts-database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: wa
      POSTGRES_PASSWORD: wa
      POSTGRES_DB: whereabouts
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - whereabouts-db-network
  whereabouts:
    container_name: whereabouts
    image: thehyve/whereabouts:0.0.1-SNAPSHOT
    ports:
      - 8086:8086
    environment:
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      DB_USER: wa
      DB_PASSWORD: wa
      DB_HOST: whereabouts-database
      DB_PORT: 5432
      DB_NAME: whereabouts
    depends_on:
      - whereabouts-database
    networks:
      - whereabouts-db-network
volumes:
  db-data:

networks:
  whereabouts-db-network:
    driver: bridge
